application:
  datasource: # Custom datasource properties for JDBC
    cachePrepStmts: true
    prepStmtCacheSize: 250
    prepStmtCacheSqlLimit: 2048
    useServerPrepStmts: true
  security:
    jwt:
      secret: 5867a8374e7c0f6284b177b48faf89e1c79d72d8
      token-validity-in-seconds: 86400 # 24 hours
      token-validity-in-seconds-for-remember-me: 2592000 # 30 days
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect

spring:
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  application:
    name: Blog
  profiles:
    active: dev
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    username: sa
    password:
  h2:
    console:
      enabled: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    show-sql: true
    format_sql: true
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true
    hibernate:
      ddl-auto: create-drop
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 259583618562-g1s3big00htpdfbj4ngmkmqlltgt97qg.apps.googleusercontent.com
            clientSecret: x8lusORzxUwBrbiPr7AVIfVH
            redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
  http:
    log-request-details: true
server:
  port: 8080
logging:
  level:
    web: debug
